export const seedUsers = [
  {
    name: 'CrowdTrust Admin',
    email: 'admin@crowdtrust.org',
    password: 'Admin@12345#',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    bio: 'Chief Compliance & Platform Integrity Officer at CrowdTrust.',
    phone: '+91 9876543210',
    location: 'Bengaluru, India',
    isEmailVerified: true,
    verificationStatus: 'verified',
  },
  {
    name: 'Dr. Aisha Patel',
    email: 'aisha@ruralhealth.org',
    password: 'Creator@12345#',
    role: 'creator',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
    bio: 'Public Health Specialist & Founder of Arogya Seva Himalayan Trust. 12+ years deploying mobile medical units.',
    phone: '+91 9811223344',
    location: 'Dehradun, Uttarakhand',
    isEmailVerified: true,
    verificationStatus: 'verified',
  },
  {
    name: 'Rajesh Sharma',
    email: 'rajesh@cleanwater.org',
    password: 'Creator@12345#',
    role: 'creator',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    bio: 'Civil Engineer & Environmental Activist specializing in solar water purification systems for arid regions.',
    phone: '+91 9822334455',
    location: 'Jaipur, Rajasthan',
    isEmailVerified: true,
    verificationStatus: 'verified',
  },
  {
    name: 'Ananya Sen',
    email: 'ananya@girlsincode.org',
    password: 'Creator@12345#',
    role: 'creator',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80',
    bio: 'Software engineer and STEM educator bringing robotics and computer science curriculum to rural schools.',
    phone: '+91 9833445566',
    location: 'Kolkata, West Bengal',
    isEmailVerified: true,
    verificationStatus: 'verified',
  },
  {
    name: 'Vikram Malhotra',
    email: 'vikram@solarnext.org',
    password: 'Creator@12345#',
    role: 'creator',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    bio: 'CleanTech innovator building affordable autonomous solar weeding machines for smallholder farmers.',
    phone: '+91 9844556677',
    location: 'Pune, Maharashtra',
    isEmailVerified: true,
    verificationStatus: 'pending',
  },
  {
    name: 'Priya Nair',
    email: 'priya@example.com',
    password: 'Donor@12345#',
    role: 'donor',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
    bio: 'Tech lead passionate about education and transparent social causes.',
    phone: '+91 9855667788',
    location: 'Mumbai, Maharashtra',
    isEmailVerified: true,
    verificationStatus: 'verified',
  },
  {
    name: 'Rohan Gupta',
    email: 'rohan@example.com',
    password: 'Donor@12345#',
    role: 'donor',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=300&q=80',
    bio: 'Angel investor and philanthropy enthusiast supporting grassroots initiatives.',
    phone: '+91 9866778899',
    location: 'Delhi, India',
    isEmailVerified: true,
    verificationStatus: 'verified',
  },
  {
    name: 'Neha Verma',
    email: 'neha@example.com',
    password: 'Donor@12345#',
    role: 'donor',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
    bio: 'Wildlife veterinarian and community supporter.',
    phone: '+91 9877889900',
    location: 'Hyderabad, Telangana',
    isEmailVerified: true,
    verificationStatus: 'verified',
  },
];
